//
//  NewsFeedModels.swift
//  VKFeed
//
//  Created by Nikita Shumskii on 18.12.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum NewsFeed {

  enum Model {
    struct Request {
        enum RequestType {
            case getNewsFeed
            case getUser
            case revealPostId(postId: Int)
            case getNextBatch
        }
    }
    struct Response {
        enum ResponseType {
            case presentNewsFeed(feed: FeedResponse, reveledPostIds: [Int])
            case presentUserInfo(userResponse: UserResponse?)
            case presentFooterLoader
        }
    }
    struct ViewModel {
        enum ViewModelType {
            case displayNewsFeed(feedViewModel: FeedViewModel)
            case displaUser(userViewModel: UserViewModel)
            case displayFooterLoader
        }
    }
  }
}

struct FeedViewModel {
    struct Cell: FeedCellViewModel {
        var postId: Int
        var iconUrlString: String
        var name: String
        var date: String
        var text: String?
        var likes: String?
        var comments: String?
        var shares: String?
        var views: String?
        var photoAttachements: [FeedCellPhotoAttachementViewModel]
        var sizes: FeedCellSizes
    }
    
    struct FeedCellPhotoAttachment: FeedCellPhotoAttachementViewModel {
        var photoUrlString: String?
        var width: Int
        var height: Int
    }
    
    let cells: [Cell]
    let footerTitle: String?
}

struct UserViewModel: TitleViewViewModel {
    var photoUrlString: String?
}
