//
//  NewsFeedService.swift
//  VKFeed
//
//  Created by Nikita Shumskii on 18.12.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

class NewsFeedService {

    private let authService: AuthService
    private let networking: Networking
    private let fetcher: DataFetcher
    
    private var feedResponse: FeedResponse?
    private var reveledPostIds = [Int]()
    
    init() {
        self.authService = SceneDelegate.shared().authService
        self.networking = NetworkService(authService: authService)
        self.fetcher = NetworkDataFetcher(networking: networking)
    }
 
    func getUser(complition: @escaping (UserResponse?) -> Void) {
        fetcher.getUser { (userResponse) in
            complition(userResponse)
        }
    }
    
    func getFeed(complition: @escaping ([Int], FeedResponse) -> Void) {
        fetcher.getFeed { [weak self] (feedResponse) in
            self?.feedResponse = feedResponse
            guard let feedResponse = self?.feedResponse else { return }
            complition(self!.reveledPostIds, feedResponse)
        }
    }
    
    func revealPostId(forPostId postId: Int, complition: @escaping ([Int], FeedResponse) -> Void) {
        reveledPostIds.append(postId)
        guard let feedResponse = self.feedResponse else { return }
        complition(reveledPostIds, feedResponse)
    }
    
}
